include:
  - project: "sk8/sk8-conf/sk8-template-ci"
    ref: main
    file:
      - "/templates/.sk8-templates.yml"

variables:
  # pour activer automatiquement la publication à chaque mise à jour (true/false) 
  MISE_A_JOUR_AUTOMATIQUE: "false"
  # Version R fixée (uniquement pour la configuration)
  R_VERSION: "4.4.1"
  # Pour forcer la regénération de l'image de mon application (true/false)
  DOCKER_FORCE_REGEN: "false"
  # En cas d'erreur dans le CI/CD, active le mode verbose (true/false)
  SK8_DEBUG: "false"
